### ISSUE TITLE
Option to compare the current document with document rendered in Confluence

### ISSUE THREAD

**Issue by hudrid** [mihaeu/cosmere#47]
Hello!
If possible, please implement a setting in _**cosmere.json**_ to be able to compare the current document with a document already rendered in Confluence. And if both documents are the same, then stop rendering for the current document.

**Comment by mihaeu** [comment]
Hey there, can you explain your use case a bit more to understand this? If I'm understanding you correctly, than this is kind of already possible by just looking at the cached files.

**Comment by hudrid** [comment]
Thanks for the quick response!
Our company has a monorepository, where documents (our documents are full of tables and different styles) are collected via pipeline from different repositories. Then the documents are published on our website and in Confluence. We have implemented a check that identical documents should not be published, but the publication of documents in Confluence is always performed, regardless of whether the documents are identical or not. Thus, the last date of changes is different for the document on the site and the document in Confluence.
<details>
<summary>an example of a document that will always be published</summary>
 
```markdown
# AdminGuide

### **Document card**

<table>
<tr>
<td> <div style="width:200px"> <b> Doc version </b></div> </td>
<td> <div style="width:300px"> 1.0 </div> </td>
</tr>
<tr>
<td> <b> Date: </b> </td>
<td> 16.08.2028 </td>
</tr>
<tr>
<td> <b> Version </b> </td>
<td> 2.0 </td>
</tr>
<tr>
<td> <b> Document type </b> </td>
<td> AdminGuide </td>
</tr>
<tr>
<td> <b> Customer </b> </td>
<td> Cust </td>
</tr>
<tr>
<td> <b> Document Status </b> </td>
<td> <span style="background-color: #DEEBFF; color: #0747A6"> <b> Validation </b> </span></td>
</tr>
</table>
```
</details>

**Comment by mihaeu** [comment]
Are you using and persisting the cache in your pipelines?

**Comment by hudrid** [comment]
The cache is not used.

What value should be specified for the `paths` parameter in pipeline? Maybe:
```yml
paths:
      - node_modules/
```
Сan you provide an example?

**Comment by mihaeu** [comment]
This looks like GitLab pipelines if I'm not mistaken. The default cache path is `build` unless you specified another one in your `comere.json` configuration. If you add the cache to the cache layer/artifact of your build step/action cosmere will check the cache before doing anything and if things match, won't do any work on Confluence.

```yaml
paths:
      - node_modules/
      - build/
```

In case you are using GitLab pipelines make sure to consider which steps write and read from and to your cache. E.g. an `npm install` step should write to the cache, all other steps should only read from that folder. The step in which cosmere converts and publishes the information has to both read and write,

**Comment by hudrid** [comment]
<details>
<summary>gitlab-ci.yml:</summary>

```yml
confluence:
  image: ...
  stage: publish
  tags:
    - pages
  cache:
    paths:
      - node_modules/
      - build/
  before_script:
    - rm -rf $DOCS_DIR
    - cp -R $CI_PROJECT_DIR/release/ $DOCS_DIR
    - ls -la $DOCS_DIR
  script:
    - npm install
    #- npm run lint
    - npm run publish
  artifacts:
    paths:
      - build
  only:
    - master
  needs:
    - job: collect_docs
      artifacts: true
```
</details>

Works only for documents without pictures.
<details>
<summary>Job Information</summary>

![image](https://github.com/mihaeu/cosmere/assets/55594483/8c616802-79b8-47cd-86ea-4900d2d2849d)

</details>
